[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["brain_games"]

[project]
name = "brain-games"
version = "0.1.0"

[project.scripts]
brain-games = "brain_games.scripts.main:main"

